GET http://localhost:3000/api/notes
content-type: application/json

{
    "content": "VS code rest client",
    "time": true
}

###
POST http://localhost:3000/api/notes/
content-type: application/json

{
    "content": "le",
    "time": true
}